const DB="media-compressor",STORE="files",CFG="config";let db,currentFile,currentKind;const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const presets={image:{high:["High Quality",.9,2160],balanced:["Balanced",.85,1440],small:["Small Size",.74,1080]},video:{social:["Social Master",10,1080],high:["High Quality",12,1080],balanced:["Balanced",8,1080],small:["Small Size",4.5,720]}};
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{r.result.createObjectStore(STORE,{keyPath:"id"});r.result.createObjectStore(CFG,{keyPath:"key"})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function tx(mode,store=STORE){return db.transaction(store,mode).objectStore(store)}
function put(v){return new Promise((r,j)=>{const q=tx("readwrite").put(v);q.onsuccess=()=>r();q.onerror=()=>j(q.error)})}
function all(){return new Promise((r,j)=>{const q=tx("readonly").getAll();q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}
function del(id){return new Promise(r=>{const q=tx("readwrite").delete(id);q.onsuccess=()=>r()})}
async function cfg(key,def){return new Promise(r=>{const q=tx("readonly",CFG).get(key);q.onsuccess=()=>r(q.result?.value??def)})}
async function setCfg(key,value){return new Promise(r=>{const q=tx("readwrite",CFG).put({key,value});q.onsuccess=()=>r()})}
function go(id,kind){$$(".page").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");if(id==="compress"&&kind)setup(kind);if(id==="files")renderFiles();if(id==="settings")loadSettings();scrollTo(0,0)}
$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go,b.dataset.kind));
function setup(kind){currentKind=kind;$("#compressTitle").textContent=kind==="image"?"Kompres Foto":"Kompres Video";$("#fileInput").accept=kind==="image"?"image/*":"video/*";const s=$("#preset");s.innerHTML=Object.entries(presets[kind]).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join("");cfg(kind+"Default",kind==="image"?"balanced":"social").then(v=>s.value=v)}
$("#fileInput").onchange=e=>loadFile(e.target.files[0]);
async function loadFile(file){if(!file)return;currentKind=file.type.startsWith("video")?"video":"image";currentFile=file;$("#original").classList.remove("hidden");$("#presets").classList.remove("hidden");$("#result").classList.add("hidden");const u=URL.createObjectURL(file);$("#original").innerHTML=`<div class="stats"><div class="stat"><small>Nama</small>${esc(file.name)}</div><div class="stat"><small>Ukuran</small>${fmt(file.size)}</div><div class="stat"><small>Tipe</small>${file.type||"unknown"}</div></div>${currentKind==="image"?`<img class="preview" src="${u}" alt="">`:`<video class="preview" src="${u}" controls playsinline></video>`}`}
$("#compressBtn").onclick=async()=>{if(!currentFile)return;showProgress("Mengompres...",5);try{const preset=$("#preset").value;const blob=currentKind==="image"?await compressImage(currentFile,presets.image[preset]):await compressVideo(currentFile,presets.video[preset]);showProgress("Menyimpan lokal...",90);const id="MC-"+Date.now()+"-"+Math.random().toString(36).slice(2,7);const ext=currentKind==="image"?"jpg":"webm";const name=`${base(currentFile.name)}_${preset.toUpperCase()}.${ext}`;const item={id,name,originalName:currentFile.name,type:currentKind,originalSize:currentFile.size,size:blob.size,blob,createdAt:Date.now(),preset,status:"PENDING"};await put(item);showProgress("Selesai",100);showResult(item);if(navigator.onLine&&await cfg("autoUpload",true))uploadItem(item)}catch(e){console.error(e);showProgress("Gagal",0);alert("Kompresi gagal: "+e.message)}};
function showProgress(label,p){$("#progress").classList.remove("hidden");$("#bar").style.width=p+"%";$("#progressText").textContent=Math.round(p)+"%";$("#progressLabel").textContent=label}
async function compressImage(file,[,quality,max]){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>{let w=im.naturalWidth,h=im.naturalHeight,s=Math.min(1,max/Math.max(w,h));w=Math.round(w*s);h=Math.round(h*s);const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(im,0,0,w,h);c.toBlob(b=>b?res(b):rej(Error("Canvas gagal")),"image/jpeg",quality);URL.revokeObjectURL(im.src)};im.onerror=()=>rej(Error("Foto tidak dapat dibaca"));im.src=URL.createObjectURL(file)})}
async function compressVideo(file,[,mbps,maxH]){if(!("MediaRecorder"in window))throw Error("Browser tidak mendukung MediaRecorder");const v=document.createElement("video");v.src=URL.createObjectURL(file);v.muted=false;v.playsInline=true;await new Promise((r,j)=>{v.onloadedmetadata=r;v.onerror=()=>j(Error("Video tidak dapat dibaca"))});const scale=Math.min(1,maxH/Math.max(v.videoWidth,v.videoHeight));const c=document.createElement("canvas");c.width=Math.round(v.videoWidth*scale);c.height=Math.round(v.videoHeight*scale);const ctx=c.getContext("2d");const stream=c.captureStream(30);try{const audio=v.captureStream().getAudioTracks();audio.forEach(t=>stream.addTrack(t))}catch{}const mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm";const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:mbps*1e6,audioBitsPerSecond:128000});const chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);const done=new Promise(r=>rec.onstop=()=>r(new Blob(chunks,{type:mime})));rec.start(1000);v.currentTime=0;await v.play();const tick=()=>{if(v.ended){rec.stop();return}ctx.drawImage(v,0,0,c.width,c.height);const p=Math.min(89,(v.currentTime/v.duration)*84+6);showProgress("Mengompres video...",p);requestAnimationFrame(tick)};tick();return done.finally(()=>{URL.revokeObjectURL(v.src);stream.getTracks().forEach(t=>t.stop())})}
function showResult(x){const save=x.originalSize?((1-x.size/x.originalSize)*100):0;$("#result").classList.remove("hidden");$("#result").innerHTML=`<h3>✓ Kompres selesai</h3><div class="stats"><div class="stat"><small>Original</small>${fmt(x.originalSize)}</div><div class="stat"><small>Hasil</small>${fmt(x.size)}</div><div class="stat"><small>Hemat</small>${Math.max(0,save).toFixed(1)}%</div></div>${x.type==="image"?`<img class="preview" src="${URL.createObjectURL(x.blob)}">`:`<video class="preview" src="${URL.createObjectURL(x.blob)}" controls playsinline></video>`}<button class="primary" onclick="downloadItem('${x.id}')">Download hasil</button><button class="ghost" onclick="uploadItemById('${x.id}')">Upload ke Drive</button>`}
async function downloadItem(id){const x=(await all()).find(a=>a.id===id);if(!x)return;const a=document.createElement("a");a.href=URL.createObjectURL(x.blob);a.download=x.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function uploadItemById(id){const x=(await all()).find(a=>a.id===id);if(x)uploadItem(x)}
async function uploadItem(x){if(!navigator.onLine)return;const url=await cfg("gasUrl","");if(!url){console.warn("GAS URL belum dikonfigurasi");return}try{const data=await blobToBase64(x.blob);const r=await fetch(url,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"uploadFile",id:x.id,name:x.name,mime:x.blob.type,type:x.type,size:x.size,data})});const out=await r.json();if(!out.ok)throw Error(out.error||"Upload gagal");x.status="UPLOADED";x.driveFileId=out.fileId;x.driveUrl=out.url;await put(x);renderFiles()}catch(e){x.status="PENDING";await put(x);console.warn(e)}}
function blobToBase64(b){return new Promise((r,j)=>{const f=new FileReader();f.onload=()=>r(f.result.split(",")[1]);f.onerror=j;f.readAsDataURL(b)})}
async function renderFiles(){const q=$("#search").value.toLowerCase(),f=$("#filter").value;let a=await all();a=a.filter(x=>(!q||x.name.toLowerCase().includes(q))&&(f==="all"||(f==="pending"&&x.status==="PENDING")||(f==="drive"&&x.status==="UPLOADED")||f===x.type)).sort((a,b)=>b.createdAt-a.createdAt);$("#fileList").innerHTML=a.length?a.map(x=>`<article class="item"><div class="thumb">${x.type==="image"?`<img src="${URL.createObjectURL(x.blob)}" class="thumb">`:"🎥"}</div><div class="meta"><b>${esc(x.name)}</b><small>${fmt(x.size)} • ${new Date(x.createdAt).toLocaleString("id-ID")}</small><div class="status ${x.status==="UPLOADED"?"ok":"pending"}">${x.status==="UPLOADED"?"LOCAL ✓ • DRIVE ✓":"LOCAL ✓ • DRIVE ⏳ MENUNGGU"}</div></div><div class="actions"><button onclick="downloadItem('${x.id}')">Download</button><button onclick="deleteItem('${x.id}')">Hapus</button></div></article>`).join(""):"<div class='card'><p class='hint'>Belum ada hasil kompres.</p></div>";updateStorage()}
async function deleteItem(id){const x=(await all()).find(a=>a.id===id);if(!x)return;if(!confirm("Hapus file lokal? File Drive tidak akan dihapus otomatis."))return;await del(id);renderFiles()}
$("#search").oninput=()=>renderFiles();$("#filter").onchange=()=>renderFiles();
async function loadSettings(){$("#imageDefault").value=await cfg("imageDefault","balanced");$("#videoDefault").value=await cfg("videoDefault","social");$("#autoUpload").checked=await cfg("autoUpload",true);$("#autoRetry").checked=await cfg("autoRetry",true);updateStorage()}
["imageDefault","videoDefault","autoUpload","autoRetry"].forEach(id=>$("#"+id).onchange=()=>{const k=id==="imageDefault"?"imageDefault":id==="videoDefault"?"videoDefault":id;setCfg(k,$("#"+id).type==="checkbox"?$("#"+id).checked:$("#"+id).value)});
$("#clearLocal").onclick=async()=>{if(!confirm("Hapus semua hasil kompres lokal?"))return;for(const x of await all())await del(x.id);renderFiles()};
async function updateStorage(){if(navigator.storage?.estimate){const s=await navigator.storage.estimate();$("#storage").textContent=`${fmt(s.usage||0)} / ${fmt(s.quota||0)}`}}
function fmt(n){if(!n)return"0 B";const u=["B","KB","MB","GB"],i=Math.floor(Math.log(n)/Math.log(1024));return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
function base(n){return n.replace(/\.[^.]+$/,"").replace(/[^\w-]+/g,"_").slice(0,60)||"media"}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
window.downloadItem=downloadItem;window.deleteItem=deleteItem;window.uploadItemById=uploadItemById;
window.addEventListener("online",async()=>{$("#net").textContent="ONLINE";if(await cfg("autoRetry",true))for(const x of await all())if(x.status==="PENDING")uploadItem(x)});
window.addEventListener("offline",()=>$("#net").textContent="OFFLINE");
openDB().then(()=>{if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");$("#net").textContent=navigator.onLine?"ONLINE":"OFFLINE";go("home")});
